# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkBfRo6o8gquwGZbi5mae8fYe6VR9Azl
"""

import google.generativeai as genai #shift+enter

from google.colab import userdata
api_key = userdata.get('My_key')

genai.configure(api_key=api_key)

prompt_template="""

        Context : you are an qa engineer you need to help to create a test cases
        and give clear understanding about the feature.
"""

list (genai.list_models())

Model=genai.GenerativeModel('gemini-1.5-flash-latest')

response = Model.generate_content(prompt_template)
response.text.strip()